/* ============================================================
   SUBSTANCE DATABASE — pH Whisperer quiz
   ============================================================
   REPLACE THE SAMPLE ENTRIES BELOW WITH YOUR OWN DATABASE.
   Format per entry:  { name: "Substance name", ph: 7.0 }
   - ph can be a single typical value (use the middle of a range)
   - aim for good coverage of the whole 1–13.5 scale
   - the quiz picks the substance closest to the measured pH as
     the correct answer, and distant ones as wrong options, so
     the more entries you add, the better the questions get.
   ============================================================ */

const SUBSTANCES = [
  { name: "Battery acid", ph: 0.8 },
  { name: "Stomach acid", ph: 1.5 },
  { name: "Lemon juice", ph: 2.2 },
  { name: "Lime juice", ph: 2.1 },
  { name: "Cola", ph: 2.5 },
  { name: "Vinegar", ph: 2.8 },
  { name: "Apple cider vinegar", ph: 3.0 },
  { name: "Orange juice", ph: 3.5 },
  { name: "Apple juice", ph: 3.6 },
  { name: "Grapefruit juice", ph: 3.3 },
  { name: "Pineapple juice", ph: 3.4 },
  { name: "Cranberry juice", ph: 2.6 },
  { name: "Tomato juice", ph: 4.1 },
  { name: "Wine", ph: 3.5 },
  { name: "Beer", ph: 4.4 },
  { name: "Coffee", ph: 5.0 },
  { name: "Espresso", ph: 5.1 },
  { name: "Black tea", ph: 5.5 },
  { name: "Green tea", ph: 6.0 },
  { name: "Herbal tea", ph: 6.5 },
  { name: "Milk", ph: 6.6 },
  { name: "Chocolate milk", ph: 6.5 },
  { name: "Soy milk", ph: 6.7 },
  { name: "Almond milk", ph: 6.6 },
  { name: "Oat milk", ph: 6.8 },
  { name: "Yogurt", ph: 4.5 },
  { name: "Buttermilk", ph: 4.6 },
  { name: "Cream", ph: 6.7 },
  { name: "Butter", ph: 6.2 },
  { name: "Egg white", ph: 8.2 },
  { name: "Egg yolk", ph: 6.1 },
  { name: "Pure water", ph: 7.0 },
  { name: "Tap water", ph: 7.3 },
  { name: "Mineral water", ph: 7.5 },
  { name: "Sparkling water", ph: 4.5 },
  { name: "Rainwater", ph: 5.6 },
  { name: "Seawater", ph: 8.1 },
  { name: "Swimming pool water", ph: 7.4 },
  { name: "Human blood", ph: 7.4 },
  { name: "Saliva", ph: 6.8 },
  { name: "Urine", ph: 6.0 },
  { name: "Sweat", ph: 5.5 },
  { name: "Tears", ph: 7.4 },
  { name: "Soap solution", ph: 10.0 },
  { name: "Hand soap", ph: 9.5 },
  { name: "Dish soap", ph: 9.0 },
  { name: "Shampoo", ph: 5.5 },
  { name: "Conditioner", ph: 4.5 },
  { name: "Body wash", ph: 5.5 },
  { name: "Toothpaste", ph: 8.0 },
  { name: "Mouthwash", ph: 6.0 },
  { name: "Baking soda solution", ph: 8.3 },
  { name: "Baking powder solution", ph: 7.2 },
  { name: "Household ammonia", ph: 11.5 },
  { name: "Bleach", ph: 12.5 },
  { name: "Drain cleaner", ph: 13.5 },
  { name: "Window cleaner", ph: 10.5 },
  { name: "Laundry detergent", ph: 10.0 },
  { name: "Dishwasher detergent", ph: 11.0 },
  { name: "Hydrogen peroxide (3%)", ph: 4.5 },
  { name: "Rubbing alcohol", ph: 7.0 },
  { name: "Hand sanitizer", ph: 7.0 },
  { name: "Acetone", ph: 7.0 },
  { name: "Nail polish remover", ph: 7.0 },
  { name: "Sodium hydroxide solution", ph: 14.0 },
  { name: "Hydrochloric acid (0.1 M)", ph: 1.0 },
  { name: "Sulfuric acid (0.1 M)", ph: 1.2 },
  { name: "Nitric acid (0.1 M)", ph: 1.1 },
  { name: "Acetic acid (0.1 M)", ph: 2.9 },
  { name: "Citric acid solution", ph: 2.3 },
  { name: "Carbonic acid", ph: 3.8 },
  { name: "Sodium bicarbonate solution", ph: 8.3 },
  { name: "Sodium carbonate solution", ph: 11.5 },
  { name: "Calcium hydroxide solution", ph: 12.4 },
  { name: "Ammonium hydroxide", ph: 11.6 },
  { name: "Distilled water", ph: 7.0 },
  { name: "Deionized water", ph: 7.0 },
  { name: "Salt water", ph: 7.0 },
  { name: "Sugar water", ph: 7.0 },
  { name: "Coconut water", ph: 5.3 },
  { name: "Sports drink", ph: 3.2 },
  { name: "Energy drink", ph: 3.3 },
  { name: "Ketchup", ph: 3.9 },
  { name: "Mustard", ph: 3.7 },
  { name: "Mayonnaise", ph: 4.2 },
  { name: "Soy sauce", ph: 4.8 },
  { name: "Hot sauce", ph: 3.1 },
  { name: "Pickle juice", ph: 3.2 },
  { name: "Honey", ph: 3.9 },
  { name: "Maple syrup", ph: 6.8 },
  { name: "Jam", ph: 3.4 },
  { name: "Gelatin dessert", ph: 3.8 },
  { name: "Ice cream", ph: 6.5 },
  { name: "Cheddar cheese", ph: 5.3 },
  { name: "Cottage cheese", ph: 4.8 },
  { name: "Sour cream", ph: 4.5 },
  { name: "Olive oil", ph: 7.0 },
  { name: "Vegetable oil", ph: 7.0 },
  { name: "Butter oil", ph: 6.5 },
  { name: "Liquid fertilizer", ph: 6.5 },
  { name: "Plant sap", ph: 6.2 },
  { name: "Compost tea", ph: 6.8 },
  { name: "Soil water", ph: 6.5 },
  { name: "Lake water", ph: 7.2 },
  { name: "River water", ph: 7.0 },
  { name: "Well water", ph: 7.5 }
];
